# Generated by Django 3.0.2 on 2021-02-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Politics', 'Politics'), ('Health', 'Health'), ('Sport', 'Sport'), ('Tech', 'Tech')], max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Posts')),
            ],
        ),
    ]
