# Generated by Django 3.0.2 on 2021-02-12 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0004_auto_20210212_0820"),
    ]

    operations = [
        migrations.RenameModel(old_name="Reactions", new_name="Reaction",),
    ]
