# Generated by Django 3.0.2 on 2021-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210217_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic']},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='like_or_dislike',
            field=models.CharField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike'), ('Neutral', 'Neutral')], max_length=255, null=True),
        ),
    ]
